import os
import json

# --- CONFIGURATION ---
# The base folder containing your media folders
BASE_IMAGE_DIR = '/usr/share/jellyfin/web/custom/ui/'
# The output JavaScript configuration file
OUTPUT_FILE    = '/usr/share/jellyfin/web/custom/ui/dyncard-config.js'
# The web-facing prefix path that the browser uses to find these files
WEB_PREFIX     = '/web/custom/ui/cards'
# ---------------------

backgrounds = {}

# os.walk recursively goes through the base directory and all subdirectories
for root, dirs, files in os.walk(BASE_IMAGE_DIR):
    # The title is the name of the immediate parent folder we are currently scanning
    title = os.path.basename(root)

    for filename in files:
        # Look for our animated anchor files
        if filename.lower().endswith('_hover.gif'):

            # Figure out what the matching static image should be named
            # e.g., "1_hover.gif" -> "1.jpg"
            base_name = filename.rsplit('_hover.gif', 1)[0]
            static_img = f"{base_name}.jpg"

            # Check if the static counterpart actually exists in this folder
            if static_img in files:

                # Create the array for this title if it's the first time we've seen it
                if title not in backgrounds:
                    backgrounds[title] = []
                
                # Calculate the relative path from the base directory
                rel_dir = os.path.relpath(root, BASE_IMAGE_DIR)

                # Construct the final web paths (forcing forward slashes for web URLs)
                if rel_dir == ".":
                    web_dir = WEB_PREFIX
                else:
                    web_dir = f"{WEB_PREFIX}/{rel_dir}".replace('\\', '/')

                backgrounds[title].append({
                    "default": f"{web_dir}/{static_img}",
                    "hover": f"{web_dir}/{filename}"
                })

# Write out the generated JavaScript dictionary
try:
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("// Auto-generated by Python Script\n")
        f.write("// Do not edit manually. Run the script to update.\n")
        f.write("window.dynamicBackgrounds = ")
        # indent=4 makes it human-readable, ensure_ascii=False preserves special characters
        json.dump(backgrounds, f, indent=4, ensure_ascii=False)
        f.write(";\n")

    # Count the results to print a success message
    total_titles = len(backgrounds)
    total_pairs = sum(len(pairs) for pairs in backgrounds.values())
    print(f"Success! Wrote {total_pairs} background pairs across {total_titles} titles to {OUTPUT_FILE}.")

except Exception as e:
    print(f"Error writing to configuration file: {e}")
