import os
import json

# --- CONFIGURATION ---
# The base folder containing your media folders
BASE_IMAGE_DIR = '/usr/share/jellyfin/web/custom/ui/'
# The output JavaScript configuration file
OUTPUT_FILE    = '/usr/share/jellyfin/web/custom/ui/dyncard-config.js'
# The web-facing prefix path that the browser uses to find these files
WEB_PREFIX     = '/web/custom/ui/cards'

# Supported image extensions
VALID_EXTS     = ('.jpg', '.jpeg', '.png', '.gif', '.webp')
# ---------------------

backgrounds = {}

for root, dirs, files in os.walk(BASE_IMAGE_DIR):
    title = os.path.basename(root)

    base_images = []
    hover_images = {}

    # Pass 1: Categorize files as either hover images or base images
    for filename in files:
        if filename.lower().endswith(VALID_EXTS):
            name, ext = os.path.splitext(filename)

            if name.lower().endswith('_hover'):
                # Strip '_hover' from the name so we can match it to the base image
                base_name = name[:-6]
                hover_images[base_name] = filename
            else:
                base_images.append(filename)

    # Pass 2: Pair them up and generate the web paths
    for base_img in base_images:
        name, _ = os.path.splitext(base_img)

        if title not in backgrounds:
            backgrounds[title] = []

        # Calculate relative path and format for the web
        rel_dir = os.path.relpath(root, BASE_IMAGE_DIR)
        if rel_dir == ".":
            web_dir = WEB_PREFIX
        else:
            web_dir = f"{WEB_PREFIX}/{rel_dir}".replace('\\', '/')

        entry = {
            "default": f"{web_dir}/{base_img}"
        }

        # If we found a matching hover image (regardless of its extension), add it
        if name in hover_images:
            entry["hover"] = f"{web_dir}/{hover_images[name]}"

        backgrounds[title].append(entry)

# Write out the generated JavaScript dictionary
try:
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("// Auto-generated by Python Script\n")
        f.write("// Do not edit manually. Run the script to update.\n")
        f.write("window.dynamicBackgrounds = ")
        json.dump(backgrounds, f, indent=4, ensure_ascii=False)
        f.write(";\n")

    total_titles = len(backgrounds)
    total_pairs = sum(len(pairs) for pairs in backgrounds.values())
    print(f"Success! Wrote {total_pairs} backgrounds across {total_titles} titles to {OUTPUT_FILE}.")

except Exception as e:
    print(f"Error writing to configuration file: {e}")
